WebApplication3/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.ViewModels
{
	public class Login
	{
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; }
		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
		public bool RememberMe { get; set; }
	}
}

WebApplication3/Pages/ChangePassword.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using WebApplication3.Model;
using WebApplication3.ViewModels;

namespace WebApplication3.Pages
{
    [ValidateAntiForgeryToken]
    public class ChangePasswordModel : PageModel
    {
        [BindProperty]
        public ChangePassword CPModel { get; set; }

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IAuditLogService _auditLogService;

        public ChangePasswordModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IAuditLogService auditLogService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _auditLogService = auditLogService;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "User not found.");
                return Page();
            }

            if (DateTime.UtcNow - user.LastPasswordChangeDate < TimeSpan.FromMinutes(10))
            {
                ModelState.AddModelError(string.Empty, "You can only change your password every 10 minutes.");
                return Page();
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(user, CPModel.OldPassword, CPModel.NewPassword);
            if (!changePasswordResult.Succeeded)
            {
                foreach (var error in changePasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return Page();
            }

            // Update the LastPasswordChangeDate to the current time after successful password change
            user.LastPasswordChangeDate = DateTime.UtcNow;
            var updateResult = await _userManager.UpdateAsync(user);
            if (!updateResult.Succeeded)
            {
                foreach (var error in updateResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return Page();
            }


            await _auditLogService.LogAsync(user.Id, "Password changed");
            
            // Redirect the user to a confirmation page or back to the form with a success message.
            return RedirectToPage("/Login");
        }
    }
}

WebApplication3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet(int? code)
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            ErrorCode = code.HasValue ? code.Value.ToString() : "Unknown";

            ErrorMessage = GetErrorMessageForStatusCode(code);
        }

        private string GetErrorMessageForStatusCode(int? code)
        {
            switch (code)
            {
                case 404:
                    return "The requested page was not found.";
                case 403:
                    return "Access is forbidden to the requested page.";
                case 500:
                    return "An internal server error occurred.";
                default:
                    return "An error occurred.";
            }
        }
    }
}

WebApplication3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.Model;

namespace WebApplication3.Pages
{
    public class IndexModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<IndexModel> _logger;

        public ApplicationUser CurrentUser { get; set; }
        public string DecryptedNRIC { get; private set; }

        public IndexModel(UserManager<ApplicationUser> userManager, ILogger<IndexModel> logger)
        {
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                _logger.LogWarning("User is not logged in.");
                return RedirectToPage("/Login");
            }

            // Check if the password needs to be changed
            if (DateTime.UtcNow - user.LastPasswordChangeDate > TimeSpan.FromMinutes(200))
            {
                _logger.LogInformation("User needs to change password.");
                return RedirectToPage("/ChangePassword"); // Redirect to ChangePassword page
            }

            // Retrieve session GUID from cookie
            var sessionGuid = Request.Cookies["Session_Id"];
            if (sessionGuid == null || sessionGuid != user.CurrentSessionId)
            {
                // Session mismatch or expired, sign out the user
                await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
                _logger.LogWarning("Session mismatch or expired. User signed out.");
                return RedirectToPage("/Login"); // Redirect to login page
            }

            CurrentUser = user;
            DecryptNRIC(user.NRIC);

            return Page();
        }

        private void DecryptNRIC(string encryptedNRIC)
        {
            try
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("SecretKey");
                DecryptedNRIC = protector.Unprotect(encryptedNRIC);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error decrypting NRIC: {ex.Message}");
                DecryptedNRIC = $"Error decrypting NRIC: {ex.Message}";
            }
        }
    }

}

WebApplication3/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.ViewModels;
using WebApplication3.Model;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;

namespace WebApplication3.Pages
{
    [ValidateAntiForgeryToken]
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login LModel { get; set; }

        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IAuditLogService _auditLogService;

        public LoginModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IAuditLogService auditLogService)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            _auditLogService = auditLogService;
        }


        public void OnGet()
        {
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {

                var user = await signInManager.UserManager.FindByEmailAsync(LModel.Email);

                if (user != null)
                {
					// Verify reCAPTCHA
					var recaptchaResponse = Request.Form["g-recaptcha-response"];
					var recaptchaSecretKey = "6LfG2WMpAAAAAKKLixCzMy64STCalxH3_rCU8nCv";

					var httpClient = new HttpClient();
					var response = await httpClient.GetStringAsync($"https://www.google.com/recaptcha/api/siteverify?secret={recaptchaSecretKey}&response={recaptchaResponse}");


					var recaptchaResult = JsonConvert.DeserializeObject<RecaptchaResponse>(response);

					if (!recaptchaResult.Success)
					{
						ModelState.AddModelError("", "reCAPTCHA validation failed. Please try again.");

						if (recaptchaResult.ErrorCodes != null)
						{
							foreach (var errorCode in recaptchaResult.ErrorCodes)
							{
								ModelState.AddModelError("", $"reCAPTCHA Error: {errorCode}");
							}
						}

						return Page();
					}

                    var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, lockoutOnFailure: true);

                    if (identityResult.Succeeded)
                    {
                        string guid = Guid.NewGuid().ToString();
                        var cookieOptions = new CookieOptions
                        {
                            HttpOnly = true,
                            Expires = DateTime.UtcNow.AddHours(1) // Set your desired expiration time
                        };
                        Response.Cookies.Append("Session_Id", guid, cookieOptions);

                        user.CurrentSessionId = guid;
                        await userManager.UpdateAsync(user);

                        await _auditLogService.LogAsync(user.Id, "User logged in");

                        return RedirectToPage("Index");
                    }
                    else if (identityResult.IsLockedOut)
                    {
                        ModelState.AddModelError("", "Account locked out. Please try again later.");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Username or Password incorrect");
                    }
                }
            }
            return Page();
        }

    }

	public class RecaptchaResponse
	{
		public bool Success { get; set; }
		public List<string> ErrorCodes { get; set; }
	}
}

WebApplication3/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.Model;

namespace WebApplication3.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IAuditLogService auditLogService;

        public LogoutModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IAuditLogService auditLogService)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.auditLogService = auditLogService;
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            var user = await userManager.GetUserAsync(User);
            if (user != null)
            {
                HttpContext.Session.Clear();
                user.CurrentSessionId = null;
                await auditLogService.LogAsync(user.Id, "User logged out");
                await userManager.UpdateAsync(user);
            }

            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

WebApplication3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.ViewModels;
using WebApplication3.Model;
using Microsoft.AspNetCore.DataProtection;
using System.Text.Encodings.Web;
using Newtonsoft.Json;
using System;

namespace WebApplication3.Pages
{
    [ValidateAntiForgeryToken]
    public class RegisterModel : PageModel
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IDataProtectionProvider _dataProtectionProvider;
        private readonly IServiceProvider serviceProvider; 

        [BindProperty]
        public Register RModel { get; set; }

        public RegisterModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IWebHostEnvironment env, ILogger<RegisterModel> logger, IDataProtectionProvider dataProtectionProvider, IServiceProvider serviceProvider)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            webHostEnvironment = env;
            _logger = logger;
            _dataProtectionProvider = dataProtectionProvider;
            this.serviceProvider = serviceProvider; 
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            _logger.LogInformation("This is a log message");
            if (ModelState.IsValid)
            {
                var recaptchaResponse = Request.Form["g-recaptcha-response"];
                var recaptchaSecretKey = "6LfG2WMpAAAAAKKLixCzMy64STCalxH3_rCU8nCv";

                var httpClient = new HttpClient();
                var response = await httpClient.GetStringAsync($"https://www.google.com/recaptcha/api/siteverify?secret={recaptchaSecretKey}&response={recaptchaResponse}");

                var recaptchaResult = JsonConvert.DeserializeObject<RecaptchaResponse>(response);

                if (!recaptchaResult.Success)
                {
                    ModelState.AddModelError("", "reCAPTCHA validation failed. Please try again.");

                    if (recaptchaResult.ErrorCodes != null)
                    {
                        foreach (var errorCode in recaptchaResult.ErrorCodes)
                        {
                            ModelState.AddModelError("", $"reCAPTCHA Error: {errorCode}");
                        }
                    }

                    return Page();
                }

                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("SecretKey");

                var existingUser = await userManager.FindByEmailAsync(RModel.Email);
                if (existingUser != null)
                {
                    ModelState.AddModelError(string.Empty, "Email address is already in use.");
                    return Page();
                }

                var user = new ApplicationUser()
                {
                    UserName = RModel.Email,
                    Email = RModel.Email,
                    FirstName = SanitizeInput(RModel.FirstName),
                    LastName = SanitizeInput(RModel.LastName),
                    Gender = SanitizeInput(RModel.Gender),
                    NRIC = protector.Protect(RModel.NRIC),
                    DateOfBirth = RModel.DateOfBirth,
                    WhoAmI = SanitizeInput(RModel.WhoAmI),
                    LastPasswordChangeDate = DateTime.UtcNow 
                };

                if (RModel.Resume != null && RModel.Resume.Length > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + "_" + RModel.Resume.FileName;
                    var filePath = Path.Combine(webHostEnvironment.ContentRootPath, @"wwwroot/uploads", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await RModel.Resume.CopyToAsync(stream);
                    }

                    // Update user's resume information
                    user.ResumePath = filePath;
                }

                var result = await userManager.CreateAsync(user, RModel.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToPage("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return Page();
        }

        // Function to sanitize user input using AntiXSS
        private string SanitizeInput(string input)
        {
            // Encode the input to prevent XSS attacks
            var sanitizedInput = HtmlEncoder.Default.Encode(input);

            return sanitizedInput;
        }
    }
}

WebApplication3/Pages/ChangePassword.cshtml
@page
@model WebApplication3.Pages.ChangePasswordModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-6">
            <h1 class="mb-3">Change Password</h1>
            <form method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="CPModel.OldPassword">Old Password</label>
                    <input type="password" asp-for="CPModel.OldPassword" class="form-control" required />
                    <span asp-validation-for="CPModel.OldPassword" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="CPModel.NewPassword">New Password</label>
                    <input type="password" asp-for="CPModel.NewPassword" class="form-control" required />
                    <span asp-validation-for="CPModel.NewPassword" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="CPModel.ConfirmNewPassword">Confirm New Password</label>
                    <input type="password" asp-for="CPModel.ConfirmNewPassword" class="form-control" required />
                    <span asp-validation-for="CPModel.ConfirmNewPassword" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Change Password</button>
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication3/Pages/Index.cshtml
@page
@model WebApplication3.Pages.IndexModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Ace Job Agency</h1>
    <p>Seize Your Dream Job.</p>
    @if (Model.CurrentUser != null)
    {
        <p>Email: @Model.CurrentUser.Email</p>
        <p>Name: @Model.CurrentUser.FirstName @Model.CurrentUser.LastName</p>
        <p>Gender: @Model.CurrentUser.Gender</p>
        <p>NRIC: @Model.DecryptedNRIC</p>
        <p>Date of Birth: @Model.CurrentUser.DateOfBirth.ToString("dd/MM/yyyy")</p>
    }
    else
    {
        <p>You are not logged in.</p>
    }
</div>

WebApplication3/Pages/Login.cshtml
@page
@model WebApplication3.Pages.LoginModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>
            <form method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Email">Email Address</label>
                    <input type="text" asp-for="LModel.Email" class="form-control" asp-antiforgery="true" />
                    <span asp-validation-for="LModel.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="LModel.Password">Password</label>
                    <input type="password" asp-for="LModel.Password" class="form-control" asp-antiforgery="true" />
                    <span asp-validation-for="LModel.Password" class="text-danger"></span>
                </div>

                <div class="mb-3 form-check">
                    <input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
                    <label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
                </div>

                <input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response" />

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    grecaptcha.ready(function () {
        grecaptcha.execute('6LfG2WMpAAAAANOko2qSb3yZUfVemKt9EJuXWH-M', { action: 'Login' }).then(function (token) {
            document.getElementById("g-recaptcha-response").value = token;
        });
    });
</script>

WebApplication3/Pages/Logout.cshtml
@page
@model WebApplication3.Pages.LogoutModel
@{
}

<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p>
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>
	</div>
</form>

WebApplication3/Pages/Register.cshtml
@page
@model WebApplication3.Pages.RegisterModel

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="mb-4">Register</h1>
            <form method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label" asp-for="RModel.FirstName">First Name</label>
                            <input type="text" asp-for="RModel.FirstName" class="form-control" asp-antiforgery="true" />
                            <span asp-validation-for="RModel.FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label" asp-for="RModel.LastName">Last Name</label>
                            <input type="text" asp-for="RModel.LastName" class="form-control" asp-antiforgery="true" />
                            <span asp-validation-for="RModel.LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Gender">Gender</label>
                    <select asp-for="RModel.Gender" class="form-control" asp-antiforgery="true">
                        <option value="">Select Gender</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                    <span asp-validation-for="RModel.Gender" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.NRIC">NRIC</label>
                    <input type="text" asp-for="RModel.NRIC" class="form-control" asp-antiforgery="true" />
                    <span asp-validation-for="RModel.NRIC" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Email">Email Address</label>
                    <input type="text" asp-for="RModel.Email" class="form-control" asp-antiforgery="true" />
                    <span asp-validation-for="RModel.Email" class="text-danger"></span>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label" asp-for="RModel.Password">Password</label>
                            <input type="password" asp-for="RModel.Password" class="form-control" asp-antiforgery="true" onkeyup="checkPasswordStrength(this.value)" />
                            <span asp-validation-for="RModel.Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
                            <input type="password" asp-for="RModel.ConfirmPassword" class="form-control" asp-antiforgery="true" />
                            <span asp-validation-for="RModel.ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <div id="passwordStrengthFeedback"></div>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.DateOfBirth">Date of Birth</label>
                    <input type="date" asp-for="RModel.DateOfBirth" class="form-control" max="@DateTime.Now.ToString("yyyy-MM-dd")" asp-antiforgery="true" />
                    <span asp-validation-for="RModel.DateOfBirth" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Resume">Resume</label>
                    <input type="file" asp-for="RModel.Resume" class="form-control" asp-antiforgery="true" />
                    <span asp-validation-for="RModel.Resume" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.WhoAmI">Who Am I</label>
                    <textarea asp-for="RModel.WhoAmI" class="form-control" asp-antiforgery="true"></textarea>
                    <span asp-validation-for="RModel.WhoAmI" class="text-danger"></span>
                </div>

                <input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response" />

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    grecaptcha.ready(function () {
        grecaptcha.execute('6LfG2WMpAAAAANOko2qSb3yZUfVemKt9EJuXWH-M', { action: 'Register' }).then(function (token) {
            document.getElementById("g-recaptcha-response").value = token;
        });
    });
    function checkPasswordStrength(password) {
        var strength = 0;
        var atChar = String.fromCharCode(64);
        var regex = new RegExp("[$" + atChar + "$!%*?&]+");

        if (/[a-z]+/.test(password)) {
            strength += 1;
        }
        if (/[A-Z]+/.test(password)) {
            strength += 1;
        }
        if (/[0-9]+/.test(password)) {
            strength += 1;
        }
        if (regex.test(password)) {
            strength += 1;
        }
        if (password.length > 12) {
            strength += 1;
        }

        var feedback = '';
        var feedbackElement = document.getElementById('passwordStrengthFeedback');
        switch (strength) {
            case 0:
            case 1:
            case 2:
            case 3:
                feedback = 'Weak';
                feedbackElement.style.color = 'red';
                break;
            case 5:
                feedback = 'Strong';
                feedbackElement.style.color = 'green';
                break;
            default:
                feedback = 'Weak';
                feedbackElement.style.color = 'red';
                break;
        }

        feedbackElement.innerText = feedback;
    }
</script>